language: node_js

node_js:
  - node

install:
  - npm install

script:
  - npm test

deploy:
  provider: npm
  email: taoabc@gmail.com
  api_key:
    secure: yHj/EBgOPVd+tglmETG/7ztM1dKsO0SrtJe1k+g7I6kHcqy6CbTLm+BZyLhMY/t5j01UeSqP0yveZmEazk4lxTi2rJTFLm5q7yzGg0pp3xRjcfzzDsS6q0T6fTqu+42eCnJFxTZLelszUgdkeX+a5hXLylCUl6b4VBfdQp++wJlfHC5CJdz4HSgZBIKoMXA3sQS7jvHu4YfCMa8ZtMBMxCYa7f2WQuJz2fUGyv5i+1w3x3zq/vcDGNsyNZXuxlN/fA258VTmq+tBQ02IhKWgd6lsbH45trEgjlvhJNX4aT+1T59nn29ooVzXIOVIJ4OLnT3pxK6RyeqqojMWMlW8VwuEHplhagfiWnoR32jgjAvpXoJqvyEiAn7QkN4jErz+aYczAAf77sW6uu+QzQXl+uh2JhA4BWYwptVGNaF8mD6UdhWOxkAzeozA24RQdxrrjMBM/TYorAVPOJq6vGQQ04u0dt9S18g2xEvz3O9hyTYH9J1mmdZEItoAprBQ2ANWsoy7OKN5BcNsY8hCJj7CoOafPU268HOs5wE7Wml6SXKWvcBEiPA/dl36+sTk3K29vCeGMaK4Vqx4QAYoJa+PLkKMQGqZkIsTr1h+/X+4nZmJTMRoddCet6Vh1PfjMDkNABMEng/mfGFGobqCXfrA2EgS/6ZzZvFNpn7baJSmu6k=
  on:
    branch: production
    repo: taoabc/dollarx