language: node_js
node_js:
- node
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: taoabc@gmail.com
  api_key:
    secure: SbFdSLBkc0W8dj0QAOBX946ZuqylGdiSmU3y6f7ZeAiUc753yzC4uBR/elYinXAwFZ/jSqrkgAd2iYOvajIy1/ogzyYrG2WhVxMr+V3wM9VTbUWjz8xb0mxWND9TvPJxkyIuXw7z/8FPTAezndQUo0E2fnjCpymh1CgKU4yYpCDfdVDuK1g8NrfcRMsD19GMGh3ZsVrHeiieMZvq0gabQqxEIG4rjHiOJJsOrJLJwTMAYI1cI77fwAJUMjoeEVIS1IWpUH2Aomr+e490wLsUmhPS/abrDq4CX7cymYnBvn+zwrwrdlEgZSzFEXPKiaWW9+EEy8j/3o7YXAElcoVeHwDnoO+9IZuBJXtFz4cDeFqMENlJJIcjBV3g0EQr+1Qx+UGeB5h3K3h1unZVVB4FKzVyv11SPCAwDM3DuMnnOc0lIJfVIxdTNhEVv8K+4edC364GEPtsF9txWstdqFCuE55NKx4EayPB3nT7EX0+Sx9JiO9K9asCE4byiD5hHq8yvxdZk7Q8r7hfZKL9mkyLf57LCLNmitoG6rsUrPqQoytPGR1iYiRSYH061VNUfHfv+uoYN+s2/r0HpDeS2ouB+jPDjHnNV3s477eDvTH6A3/fPfdnQdRzRRBYx2/qzaIq/CTl2JPEypaIqd7SkO5hGWuxEfym1UHaOjxYjQtJ6Fo=
  on:
    branch: production
